# This file has been autogenerated by the pywayland scanner

# Copyright © 2018 Ilia Bozhinov
# Copyright © 2020 Isaac Freund
# Copyright © 2024 Victoria Brekenfeld
#
# Permission to use, copy, modify, distribute, and sell this
# software and its documentation for any purpose is hereby granted
# without fee, provided that the above copyright notice appear in
# all copies and that both that copyright notice and this permission
# notice appear in supporting documentation, and that the name of
# the copyright holders not be used in advertising or publicity
# pertaining to distribution of the software without specific,
# written prior permission.  The copyright holders make no
# representations about the suitability of this software for any
# purpose.  It is provided "as is" without express or implied
# warranty.
#
# THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
# SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
# SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
# THIS SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource

from .cosmic_workspace_unstable_v1 import ZcosmicWorkspaceHandleV1
from pywayland.protocol.ext_foreign_toplevel_list_v1 import ExtForeignToplevelHandleV1
from pywayland.protocol.ext_foreign_toplevel_list_v1 import ExtForeignToplevelHandleV1Proxy
from pywayland.protocol.ext_workspace_v1 import ExtWorkspaceHandleV1
from pywayland.protocol.wayland import WlOutput


class ZcosmicToplevelHandleV1(Interface):
    """An open toplevel

    A :class:`ZcosmicToplevelHandleV1` object represents an open toplevel
    window. A single app may have multiple open toplevels.

    Each toplevel has a list of outputs it is visible on, exposed to the client
    via the output_enter and output_leave events.
    """

    name = "zcosmic_toplevel_handle_v1"
    version = 3

    class state(enum.IntEnum):
        maximized = 0
        minimized = 1
        activated = 2
        fullscreen = 3
        sticky = 4


class ZcosmicToplevelInfoV1(Interface):
    """List toplevels and properties thereof

    The purpose of this protocol is to enable clients such as taskbars or docks
    to access a list of opened applications and basic properties thereof.

    It thus extends ext_foreign_toplevel_v1 to provide more information and
    actions on foreign toplevels.
    """

    name = "zcosmic_toplevel_info_v1"
    version = 3


class ZcosmicToplevelHandleV1Resource(Resource[ZcosmicToplevelHandleV1]):
    interface = ZcosmicToplevelHandleV1

    @ZcosmicToplevelHandleV1.event()
    def closed(self) -> None:
        """The toplevel has been closed

        The server will emit no further events on the
        :class:`ZcosmicToplevelHandleV1` after this event. Any requests
        received aside from the destroy request will be ignored. Upon receiving
        this event, the client should make the destroy request to allow freeing
        of resources.

        Note: This event will not be emitted for clients binding version 2 of
        this protocol, as `:func:`ExtForeignToplevelHandleV1.closed()
        <pywayland.protocol.ext_foreign_toplevel_list_v1.ExtForeignToplevelHandleV1.closed>``
        is equivalent.
        """
        self._post_event(0)

    @ZcosmicToplevelHandleV1.event()
    def done(self) -> None:
        """All information about the toplevel has been sent

        This event is sent after all changes in the toplevel state have been
        sent.

        This allows changes to the :class:`ZcosmicToplevelHandleV1` properties
        to be seen as atomic, even if they happen via multiple events.

        Note: this is is not sent after the closed event.

        Note: This event will not be emitted for clients binding version 2 of
        this protocol, as `:func:`ExtForeignToplevelHandleV1.done()
        <pywayland.protocol.ext_foreign_toplevel_list_v1.ExtForeignToplevelHandleV1.done>``
        is equivalent.
        """
        self._post_event(1)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.String),
    )
    def title(self, title: str) -> None:
        """Title change

        This event is emitted whenever the title of the toplevel changes.

        Note: This event will not be emitted for clients binding version 2 of
        this protocol, as `:func:`ExtForeignToplevelHandleV1.title()
        <pywayland.protocol.ext_foreign_toplevel_list_v1.ExtForeignToplevelHandleV1.title>``
        is equivalent.

        :param title:
        :type title:
            `ArgumentType.String`
        """
        self._post_event(2, title)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.String),
    )
    def app_id(self, app_id: str) -> None:
        """App_id change

        This event is emitted whenever the app_id of the toplevel changes.

        Note: This event will not be emitted for clients binding version 2 of
        this protocol, as `:func:`ExtForeignToplevelHandleV1.app_id()
        <pywayland.protocol.ext_foreign_toplevel_list_v1.ExtForeignToplevelHandleV1.app_id>``
        is equivalent.

        :param app_id:
        :type app_id:
            `ArgumentType.String`
        """
        self._post_event(3, app_id)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=WlOutput),
    )
    def output_enter(self, output: WlOutput) -> None:
        """Toplevel entered an output

        This event is emitted whenever the toplevel becomes visible on the
        given output. A toplevel may be visible on multiple outputs.

        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        """
        self._post_event(4, output)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=WlOutput),
    )
    def output_leave(self, output: WlOutput) -> None:
        """Toplevel left an output

        This event is emitted whenever the toplevel is no longer visible on a
        given output. It is guaranteed that an output_enter event with the same
        output has been emitted before this event.

        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        """
        self._post_event(5, output)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=ZcosmicWorkspaceHandleV1),
    )
    def workspace_enter(self, workspace: ZcosmicWorkspaceHandleV1) -> None:
        """Toplevel entered an workspace

        This event is emitted whenever the toplevel becomes visible on the
        given workspace. A toplevel may be visible on multiple workspaces.

        :param workspace:
        :type workspace:
            :class:`~pywayland.protocol.cosmic_workspace_unstable_v1.ZcosmicWorkspaceHandleV1`
        """
        self._post_event(6, workspace)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=ZcosmicWorkspaceHandleV1),
    )
    def workspace_leave(self, workspace: ZcosmicWorkspaceHandleV1) -> None:
        """Toplevel left an workspace

        This event is emitted whenever the toplevel is no longer visible on a
        given workspace. It is guaranteed that an workspace_enter event with
        the same workspace has been emitted before this event.

        :param workspace:
        :type workspace:
            :class:`~pywayland.protocol.cosmic_workspace_unstable_v1.ZcosmicWorkspaceHandleV1`
        """
        self._post_event(7, workspace)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.Array),
    )
    def state(self, state: list) -> None:
        """The toplevel state changed

        This event is emitted once on creation of the
        :class:`ZcosmicToplevelHandleV1` and again whenever the state of the
        toplevel changes.

        :param state:
        :type state:
            `ArgumentType.Array`
        """
        self._post_event(8, state)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=WlOutput),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        version=2,
    )
    def geometry(self, output: WlOutput, x: int, y: int, width: int, height: int) -> None:
        """The toplevel's position and/or size has changed

        Emitted when the geometry of a toplevel (it's position and/or size)
        relative to the provided output has changed.

        This event is emitted once on creation of the
        :class:`ZcosmicToplevelHandleV1` for every entered output and again
        whenever the geometry of the toplevel changes relative to any output.

        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        :param x:
            x coordinate of the upper-left corner
        :type x:
            `ArgumentType.Int`
        :param y:
            y coordinate of the upper-left corner
        :type y:
            `ArgumentType.Int`
        :param width:
            width of the toplevel
        :type width:
            `ArgumentType.Int`
        :param height:
            height of the toplevel
        :type height:
            `ArgumentType.Int`
        """
        self._post_event(9, output, x, y, width, height)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=ExtWorkspaceHandleV1),
        version=3,
    )
    def ext_workspace_enter(self, workspace: ExtWorkspaceHandleV1) -> None:
        """Toplevel entered an workspace

        This event is emitted whenever the toplevel becomes visible on the
        given workspace. A toplevel may be visible on multiple workspaces.

        :param workspace:
        :type workspace:
            :class:`~pywayland.protocol.ext_workspace_v1.ExtWorkspaceHandleV1`
        """
        self._post_event(10, workspace)

    @ZcosmicToplevelHandleV1.event(
        Argument(ArgumentType.Object, interface=ExtWorkspaceHandleV1),
        version=3,
    )
    def ext_workspace_leave(self, workspace: ExtWorkspaceHandleV1) -> None:
        """Toplevel left an workspace

        This event is emitted whenever the toplevel is no longer visible on a
        given workspace. It is guaranteed that an workspace_enter event with
        the same workspace has been emitted before this event.

        :param workspace:
        :type workspace:
            :class:`~pywayland.protocol.ext_workspace_v1.ExtWorkspaceHandleV1`
        """
        self._post_event(11, workspace)


class ZcosmicToplevelInfoV1Resource(Resource[ZcosmicToplevelInfoV1]):
    interface = ZcosmicToplevelInfoV1

    @ZcosmicToplevelInfoV1.event(
        Argument(ArgumentType.NewId, interface=ZcosmicToplevelHandleV1),
    )
    def toplevel(self, toplevel: ZcosmicToplevelHandleV1) -> None:
        """A toplevel has been created

        This event is never emitted for clients binding version 2 of this
        protocol, they should use `get_cosmic_toplevel` instead.

        This event is emitted for clients binding version 1 whenever a new
        toplevel window is created. It is emitted for all toplevels, regardless
        of the app that has created them.

        All initial properties of the toplevel (title, app_id, states, etc.)
        will be sent immediately after this event via the corresponding events
        in
        :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`.

        :param toplevel:
        :type toplevel:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        self._post_event(0, toplevel)

    @ZcosmicToplevelInfoV1.event()
    def finished(self) -> None:
        """The compositor has finished with the toplevel manager

        This event indicates that the compositor is done sending events to the
        :class:`ZcosmicToplevelInfoV1`. The server will destroy the object
        immediately after sending this request, so it will become invalid and
        the client should free any resources associated with it.

        Note: This event is emitted immediately after calling `stop` for
        clients binding version 2 of this protocol for backwards compatibility.
        """
        self._post_event(1)

    @ZcosmicToplevelInfoV1.event(version=2)
    def done(self) -> None:
        """All information about active toplevels have been sent

        This event is sent after all changes for currently active
        :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        have been sent.

        This allows changes to multiple
        :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        handles and their properties to be seen as atomic, even if they happen
        via multiple events.
        """
        self._post_event(2)


class ZcosmicToplevelHandleV1Proxy(Proxy[ZcosmicToplevelHandleV1]):
    interface = ZcosmicToplevelHandleV1

    @ZcosmicToplevelHandleV1.request()
    def destroy(self) -> None:
        """Destroy the :class:`ZcosmicToplevelHandleV1` object

        This request should be called either when the client will no longer use
        the :class:`ZcosmicToplevelHandleV1`.
        """
        self._marshal(0)
        self._destroy()


class ZcosmicToplevelInfoV1Proxy(Proxy[ZcosmicToplevelInfoV1]):
    interface = ZcosmicToplevelInfoV1

    @ZcosmicToplevelInfoV1.request()
    def stop(self) -> None:
        """Stop sending events

        This request indicates that the client no longer wishes to receive
        events for new toplevels.  However, the compositor may emit further
        toplevel_created events until the finished event is emitted.

        The client must not send any more requests after this one.

        Note: This request isn't necessary for clients binding version 2 of
        this protocol and will be ignored.
        """
        self._marshal(0)

    @ZcosmicToplevelInfoV1.request(
        Argument(ArgumentType.NewId, interface=ZcosmicToplevelHandleV1),
        Argument(ArgumentType.Object, interface=ExtForeignToplevelHandleV1),
        version=2,
    )
    def get_cosmic_toplevel(
        self, foreign_toplevel: ExtForeignToplevelHandleV1Proxy
    ) -> ZcosmicToplevelHandleV1Proxy:
        """Get cosmic toplevel extension object

        Request a
        :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        extension object for an existing
        :class:`~pywayland.protocol.ext_foreign_toplevel_list_v1.ExtForeignToplevelHandleV1`.

        All initial properties of the toplevel (states, etc.) will be sent
        immediately after this event via the corresponding events in
        :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`.

        :param foreign_toplevel:
        :type foreign_toplevel:
            :class:`~pywayland.protocol.ext_foreign_toplevel_list_v1.ExtForeignToplevelHandleV1`
        :returns:
            :class:`~pywayland.protocol.cosmic_toplevel_info_unstable_v1.ZcosmicToplevelHandleV1`
        """
        cosmic_toplevel = self._marshal_constructor(1, ZcosmicToplevelHandleV1, foreign_toplevel)
        return cosmic_toplevel


class ZcosmicToplevelHandleV1Global(Global[ZcosmicToplevelHandleV1]):
    interface = ZcosmicToplevelHandleV1


class ZcosmicToplevelInfoV1Global(Global[ZcosmicToplevelInfoV1]):
    interface = ZcosmicToplevelInfoV1


ZcosmicToplevelHandleV1._gen_c()
ZcosmicToplevelHandleV1.proxy_class = ZcosmicToplevelHandleV1Proxy
ZcosmicToplevelHandleV1.resource_class = ZcosmicToplevelHandleV1Resource
ZcosmicToplevelHandleV1.global_class = ZcosmicToplevelHandleV1Global


ZcosmicToplevelInfoV1._gen_c()
ZcosmicToplevelInfoV1.proxy_class = ZcosmicToplevelInfoV1Proxy
ZcosmicToplevelInfoV1.resource_class = ZcosmicToplevelInfoV1Resource
ZcosmicToplevelInfoV1.global_class = ZcosmicToplevelInfoV1Global
